name: Update Einsätze

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run script
        env:
          DIVERA_API_KEY: ${{ secrets.DIVERA_API_KEY }}
        run: python einsaetze.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.name "github-actions[bot]"
          git add einsaetze.html
          git commit -m "Update einsaetze" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
